spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
  datasource:
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
    url: ${POSTGRES_JDBC}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}


  jpa:
    properties:
      hibernate:
        c3p0:
          timeout: 30000
  application:
    name: event-router${TENANT_ID:}
encryption:
  require-data-encryption: true
  key: ${ENCRYPTION_KEY:}
springdoc:
  api-docs:
    path: /api-docs

